### ISSUE TITLE
Where to get support/ask questions about Thunderbird WebExtensions

### ISSUE THREAD

**Issue by oliviermartin** [thundernest/webext-docs#15]
The document does not have a link to say where to ask/find support/question on Thunderbird WebExtensions.

And in case someone knows, I am looking for the API (if it exists) to send me an event to notify when a new email arrive. I guess I could abuse of the `message` API to periodically list messages and make a diff to know which message is new. But it would be much more efficient to get a notification when a new message/email arrive.

**Comment by darktrojan** [comment]
That is a valid point and I will add some help links to the front page.
