### ISSUE TITLE
rename browserAction to toolbarAction - at least in the webpage

### ISSUE THREAD

**Issue by opto** [thundernest/webext-docs#30]
https://github.com/thundernest/webext-docs/blob/78/browserAction.rst

This page desccribes browserActions.
The forth line down reads: 'Use toolbar actions to put icons...'

Never heard of these and started to look in FF api docu what they are, because there are no toolbarActions in our api list.

Later I discovered that the text goes on using toolbarActions.
e.g.
"setTitle(details)
Sets the title of the toolbar action."

Proposal: better clarify in the doc that browserAction === toolbarAction, respectively, rename or allow both (just as we have browser.something and messenger.something)

**Comment by darktrojan** [comment]
How about a sentence that says "This namespace is called browserAction for compatibility with browser WebExtensions."

**Comment by opto** [comment]
thanks, I meant it the other way round. As we primarily use the word toolbarAction, maybe say something like:

'For Thunderbird, we use toolbarAction synonimously with browserAction' (or similiar). 

Its my second language, so there might be much better wording.

Would it be easy/difficult to allow use of browserAction and toolbarAction, such as we do it with browser and messenger?

**Comment by darktrojan** [comment]
That isn't easy to do, and having recently spent about a day just trying to keep the messenger alias working with upcoming changes, I'm not particularly open to the suggestion.

**Comment by opto** [comment]
it is not meant to create unnecessary work.

So maybe just mention on that page that browserAction and toolbarAction are the same thing. Meaning: on MDN, I search for browserAction to get more info, and here I search for either.

**Comment by jobisoft** [comment]
@opto: Nowhere in our documents we use the term `toolbarAction`. I see that the term `browserAction` is not intuitive, but as we get that from the mozilla codebase, changing it will cause all sorts of problems. Developers already familiar with WebExtensions (from chrome or Firefox) will get confused as well. So we have to get used to it.

**Comment by opto** [comment]
I don't want to change that in the code.
What I meant is that it might help if the documentation clearly says that the browseraction in our case is actually a toolbaraction (or similiar).


The apiDoc text text jumps from one notion (browseraction) to the other (toolbaraction) without explaining that it is the same.:


"Many of our sample extensions use a browserAction.
Use toolbar actions to put icons in the mail window toolbar. "
https://thunderbird-webextensions.readthedocs.io/en/78/browserAction.html

That is a bit weird. Put in between something like: For TB, a browserAction actually is a toolbarAction, even if called by the FF name browserAction.

**Comment by jobisoft** [comment]
Ok, did not find those from your description. This is due to the underlying common toolbar action code for browserAction, composeAction and messageDisplayAction. They all are toolbar actions in the sense that they are added to toolbars. browserAction is just one of them. I will rephrase that.

**Comment by jobisoft** [comment]
Done.
