### ISSUE TITLE
do we explain onClick.addlistener somewhere for browser/messageDisplay etc - action?

### ISSUE THREAD

**Issue by opto** [thundernest/webext-docs#32]
do we explain this somewhere:
browser.browserAction.onClicked.addListener(klickaktion);

maybe it should go into the explanation of onClicked?

while it might be implied that such an addlistener exists, it is not obvious whether it would be called addlistener or addeventlister or addclicklistener.

But maybe it is explained somewhere and I just looked in the wrong place?

Klaus

**Comment by darktrojan** [comment]
It's the same for all API events.

**Comment by jobisoft** [comment]
I added a section in the latest branch of the docs in the how to section:
https://thunderbird-webextensions.readthedocs.io/en/latest/how-to/experiments.html

Will backport this soon to the 78 and 68 branches.
