### ISSUE TITLE
Document encoding of messages.getRaw()

### ISSUE THREAD

**Issue by lieser** [thundernest/webext-docs#50]
Then I first started to use `messages.getRaw()`, I failed to probably think about encoding, until the first bug report came in.
To avoid others from making the same mistake, I think it would be good to explicitly mention the encoding ([binary string](https://developer.mozilla.org/en-US/docs/Web/API/DOMString/Binary)) in the documentation.

**Comment by jobisoft** [comment]
I added the information. Thanks for helping out.
