### ISSUE TITLE
`redirect` and `template` types

### ISSUE THREAD

**Issue by ovari** [thundernest/webext-docs#51]
Should the `type` property also include `redirect` and `template` to become:
* added a `type` property to [ComposeDetails](https://webextension-api.thunderbird.net/en/latest/compose.html#compose-composedetails), to distinguish between `new`, `reply`, `forward`,`redirect` , `draft` and `template`

https://webextension-api.thunderbird.net/en/latest/changes/beta88.html#compose

Thank you

**Comment by jobisoft** [comment]
Discussion is here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1696646

Please give details what redirect type is and what it could be usefull for.
