### ISSUE TITLE
addressBooks.provider.onSearchRequest listener should return {results, isCompleteResult}

### ISSUE THREAD

**Issue by bencomp** [thundernest/webext-docs#61]
As a beginner in developing MailExtensions, I tried creating an extension that always returns the same hardcoded contact details for a query. I followed the [`addressBooks.provider` documentation for TB 91][apdocs] and based the code on the example in there, but couldn't get it to work. I'm on Thunderbird 91.11.0 and loaded the addon as a temporary addon.

Through debugging I got the impression that my listener is indeed called, but that the array of `ContactProperties` objects wasn't accepted as a result. 

Lines 91-95 in chrome://messenger/content/parent/ext-addressBook.js call my listener and assign the results:

```js
let { results, isCompleteResult } = await this.fire.async(
   addressBookCache.convert(addressBookCache.addressBooks.get(this.UID)),
   aSearchString,
   aQuery
);
```
The next lines try to create contact cards from the `results`, but `results` would always be undefined.
Eventually I got a 'contact' after a search when I wrapped the array in an object:

```js
let response = {results: arrayOfContactProperties, isCompleteResult: false};
return response;
```

It looks like the type of the return value needs to be different. Is my analysis correct?

For reference, the working background script is below.

<details><summary>background.js</summary>

```
listener = browser.addressBooks.provider.onSearchRequest.addListener(async (node, searchString, query) => {
  console.log(node, searchString, query);
  console.log(this);
  // Return an array of ContactProperties.
  let details = [
    {
      "id": "03b6ddc3-290e-9747-95a9-aa1c71f00c96",
        "PreferMailFormat": "0",
        "DisplayName": "Bla die Bla",
        "PrimaryEmail": "iets@nogiets.nl",
        "FirstName": "Bla",
        "LastName": "die Bla"
    }
  ];
  let response = {results: details, isCompleteResult: false};
  console.log(response);
  return response;
}, {
  addressBookName: "Demo Book",
  isSecure: true,
});

console.log("The listener is", listener);
```

</details>

[apdocs]: https://webextension-api.thunderbird.net/en/91/addressBooks.provider.html

**Comment by jobisoft** [comment]
Thanks! Yes, the documentation is wrong. Will update it as soon as I can (but I will be away for the next 3 weeks)

**Comment by bencomp** [comment]
Thanks for your quick response! Glad my adventure wasn't for nothing.

If I wanted to suggest a change, should I create a PR against the 91 branch, or the default branch?

**Comment by jobisoft** [comment]
These are the relevant files on master:
- https://github.com/thundernest/webext-docs/blob/master/includes/addressBooks/onSearchRequest.js#L11
- https://github.com/thundernest/webext-docs/blob/master/overlay/addressBook.json#L149-L153

But we have to fix them on 102 and 91 as well. A PR would of course be appreciated.

**Comment by jobisoft** [comment]
Documentation has been updated! Thanks!
