### ISSUE TITLE
The Promise of beginForward() ist not beeing fulfilled or rejected

### ISSUE THREAD

**Issue by pLafarre** [thundernest/webext-docs#66]
I try to use the beginForward() function from compose. It opens a new message compose window as it says, but it seems like the promise that's beeing returned never gets fulfilled or rejected. If i use the async/await or the .then()/.catch() syntax it simply doesn't do anything after the point that the window gets opened and if i don't, im left with the pending promise instead of the tab that i need.

I also tried using the beginNew() method instead but it's the same issue there.

**Comment by jobisoft** [comment]
Hi,

could you file a WebExtension bug for this issue?

https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird&component=Add-Ons%3A+Extensions+API

Thanks!
